"""fix

Revision ID: cfb5001b9ed6
Revises: 
Create Date: 2019-11-28 11:13:34.787618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cfb5001b9ed6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interface', 'url',
               existing_type=mysql.VARCHAR(length=1024),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interface', 'url',
               existing_type=mysql.VARCHAR(length=1024),
               nullable=False)
    # ### end Alembic commands ###
