SECRET_KEY = '2343SDEWQERsHwer&^23cA'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://root:123456@localhost:3306/chen?charset=UTF8MB4'

DEBUG = True
TESTING = True
WTF_CSRF_ENABLED = False